# Generated by Django 3.1.1 on 2020-11-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=7)),
                ('present', models.IntegerField()),
                ('total_class', models.IntegerField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_m.cls')),
            ],
        ),
    ]
